app:
  port: 8000
  cors:
    allowedOrigins:
      - http://localhost:5173
      - http://localhost:5174

mongodb:
  uri: mongodb://127.0.0.1:27017/datingapp

redis:
  url: redis://127.0.0.1:6379

jwt:
  secret: change-me
  expiresIn: 7d

encryption:
  key: 0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcddd